atom/atom/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chatbot/', include('chatbot.urls')),
]

atom/chatbot/urls.py
from django.conf.urls import url
from . import views

app_name = 'chatbot'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^chatbot_help/$', views.chatbot_help, name='chatbot_help'),
    url(r'^developers/$', views.developers, name='developers'),
]

atom/chatbot/models.py
from django.db import models

# Create your models here.

atom/chatbot/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'chatbot/index.html')


def chatbot_help(request):
    return render(request, 'chatbot/help.html')


def developers(request):
    return render(request, 'chatbot/developers.html')

atom/chatbot/templates/chatbot/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ATOM | {% block title %}{% endblock %}</title>

    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'chatbot:index' %}">ATOM ChatBot</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav navbar-right">
                <li  class="{% block developers_active %}{% endblock %}">
                    <a href="{% url 'chatbot:developers' %}">
                        <span class="glyphicon glyphicon-sunglasses" aria-hidden="true"></span>&nbsp; Developers
                    </a>
                </li>
                <li  class="{% block chatbot_help_active %}{% endblock %}">
                    <a href="{% url 'chatbot:chatbot_help' %}">
                        <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp; Help
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
<footer class="col-sm-12 navbar-fixed-bottom">
    <hr color="#00000"/>
    <p>&copy; {% now "Y" %} - Atom ChatBot, by SonowalzLabs Inc.</p>
</footer>
</body>
</html>

atom/chatbot/templates/chatbot/developers.html
{% extends 'chatbot/base.html' %}
{% block title %}Developers{% endblock %}

{% block body %}
<div class="developers-container container-fluid">

    <!-- Developers -->
    <div class="row">
        <div class="row">
        <div class="col-md-5 text-center">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Developers</h3>
                    <p>Sanjib Sonowal, tweet @SonowalzLabs</p>
                    <p>Email: sanjib.s@live.com</p>
                </div>
            </div>
        </div>
    </div>
    </div>

</div>
{% endblock %}

atom/chatbot/templates/chatbot/help.html
{% extends 'chatbot/base.html' %}
{% block title %}Help{% endblock %}

{% block body %}
<div class="help-container container-fluid">

    <!-- Help -->
    <div class="row">
        <div class="col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>What is ATOM?</h3>
                    <p>ATOM is a chat bot and can answer to any of your queries.</p>
                    <h3>Where to start?</h3>
                    <p>
                        In homepage, just type in any query into the text panel that you want to ask.
                        Atom will try to provide you the best possible information.
                    </p>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

atom/chatbot/templates/chatbot/index.html
{% extends 'chatbot/base.html' %}
{% block title %}Welcome{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="chat">
            <div class="chat-title">
                <h1>I am ATOM</h1>
                <h2>How can I help you?</h2>
                <figure class="avatar">
		            <img src="static/res/botim.png" />
                </figure>
            </div>
            <div class="chat col-sm-12 text-center">
                <div class="messages">
                    <div class="messages-content"></div>
                </div>
                <div class="message-box">
                    <textarea type="text" class="message-input" placeholder="Type a message"></textarea>
                    <button type="submit" class="message-submit">Send</button>
                </div>
            </div>
        </div>
        <div class="bg"></div>
    </div>

</div>
{% endblock %}